### PR TITLE
sflock2's office changes fix

### PR DESCRIPTION
**Pull request by doomedraven**
0.3.18 didn't pick correctly office fixes, had to release

### CODE REVIEW

**Comment by doomedraven** [comment]
btw don't merge it yet, im doing full review, as i spot that rar.py was expecting pass as bytes and the rest pass as string, im activating github actions for autotests, so i will be back once i finished review i hope today

**Comment by doomedraven** [comment]
ok its done now, i have also fully remove `six` requirement so we can remove it from requirements as i don't see that you use it

**Comment by doomedraven** [comment]
there now tests to ensure that nothing is broken https://github.com/doomedraven/sflock/runs/3087298856

**Review by nazywam — APPROVED** [review]
cc @psrok1

**Comment by doomedraven** [comment]
so for extractors it should be more than stable now, as you didn't pick the office i just change it to latest version, but changes in .22 and .23 is more for file recon fixes than archives

**Comment by nazywam** [comment]
Thanks!

**Pull request merged**
